// Code generated by protoc-gen-go. DO NOT EDIT.
// source: laptop_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateLaptopRequest struct {
	Laptop               *Laptop  `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLaptopRequest) Reset()         { *m = CreateLaptopRequest{} }
func (m *CreateLaptopRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLaptopRequest) ProtoMessage()    {}
func (*CreateLaptopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240c60d9fb227e71, []int{0}
}

func (m *CreateLaptopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLaptopRequest.Unmarshal(m, b)
}
func (m *CreateLaptopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLaptopRequest.Marshal(b, m, deterministic)
}
func (m *CreateLaptopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLaptopRequest.Merge(m, src)
}
func (m *CreateLaptopRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLaptopRequest.Size(m)
}
func (m *CreateLaptopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLaptopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLaptopRequest proto.InternalMessageInfo

func (m *CreateLaptopRequest) GetLaptop() *Laptop {
	if m != nil {
		return m.Laptop
	}
	return nil
}

type FindLaptopRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLaptopRequest) Reset()         { *m = FindLaptopRequest{} }
func (m *FindLaptopRequest) String() string { return proto.CompactTextString(m) }
func (*FindLaptopRequest) ProtoMessage()    {}
func (*FindLaptopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_240c60d9fb227e71, []int{1}
}

func (m *FindLaptopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLaptopRequest.Unmarshal(m, b)
}
func (m *FindLaptopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLaptopRequest.Marshal(b, m, deterministic)
}
func (m *FindLaptopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLaptopRequest.Merge(m, src)
}
func (m *FindLaptopRequest) XXX_Size() int {
	return xxx_messageInfo_FindLaptopRequest.Size(m)
}
func (m *FindLaptopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLaptopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindLaptopRequest proto.InternalMessageInfo

func (m *FindLaptopRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateLaptopResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLaptopResponse) Reset()         { *m = CreateLaptopResponse{} }
func (m *CreateLaptopResponse) String() string { return proto.CompactTextString(m) }
func (*CreateLaptopResponse) ProtoMessage()    {}
func (*CreateLaptopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240c60d9fb227e71, []int{2}
}

func (m *CreateLaptopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLaptopResponse.Unmarshal(m, b)
}
func (m *CreateLaptopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLaptopResponse.Marshal(b, m, deterministic)
}
func (m *CreateLaptopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLaptopResponse.Merge(m, src)
}
func (m *CreateLaptopResponse) XXX_Size() int {
	return xxx_messageInfo_CreateLaptopResponse.Size(m)
}
func (m *CreateLaptopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLaptopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLaptopResponse proto.InternalMessageInfo

func (m *CreateLaptopResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindLaptopResponse struct {
	Laptop               *Laptop  `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindLaptopResponse) Reset()         { *m = FindLaptopResponse{} }
func (m *FindLaptopResponse) String() string { return proto.CompactTextString(m) }
func (*FindLaptopResponse) ProtoMessage()    {}
func (*FindLaptopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_240c60d9fb227e71, []int{3}
}

func (m *FindLaptopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindLaptopResponse.Unmarshal(m, b)
}
func (m *FindLaptopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindLaptopResponse.Marshal(b, m, deterministic)
}
func (m *FindLaptopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindLaptopResponse.Merge(m, src)
}
func (m *FindLaptopResponse) XXX_Size() int {
	return xxx_messageInfo_FindLaptopResponse.Size(m)
}
func (m *FindLaptopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindLaptopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindLaptopResponse proto.InternalMessageInfo

func (m *FindLaptopResponse) GetLaptop() *Laptop {
	if m != nil {
		return m.Laptop
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateLaptopRequest)(nil), "example.com.CreateLaptopRequest")
	proto.RegisterType((*FindLaptopRequest)(nil), "example.com.FindLaptopRequest")
	proto.RegisterType((*CreateLaptopResponse)(nil), "example.com.CreateLaptopResponse")
	proto.RegisterType((*FindLaptopResponse)(nil), "example.com.FindLaptopResponse")
}

func init() {
	proto.RegisterFile("laptop_service.proto", fileDescriptor_240c60d9fb227e71)
}

var fileDescriptor_240c60d9fb227e71 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x49, 0x2c, 0x28,
	0xc9, 0x2f, 0x88, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x4e, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x4b, 0xce, 0xcf, 0x95, 0x82, 0x29,
	0xc9, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x87, 0x2a, 0x51, 0x72, 0xe2, 0x12, 0x76, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0xf5, 0x01, 0xcb, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x69, 0x73, 0xb1,
	0x41, 0x94, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x09, 0xeb, 0x21, 0x19, 0xa5, 0x07, 0x55,
	0x0b, 0x55, 0xa2, 0xa4, 0xcc, 0x25, 0xe8, 0x96, 0x99, 0x97, 0x82, 0x6a, 0x02, 0x1f, 0x17, 0x53,
	0x66, 0x0a, 0x58, 0x37, 0x67, 0x10, 0x53, 0x66, 0x8a, 0x92, 0x1a, 0x97, 0x08, 0xaa, 0x45, 0xc5,
	0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x18, 0xea, 0x1c, 0xb9, 0x84, 0x90, 0x0d, 0x83, 0xaa, 0x22, 0xc5,
	0x3d, 0x46, 0xdb, 0x19, 0xb9, 0x78, 0x21, 0x42, 0xc1, 0x90, 0xe0, 0x10, 0x0a, 0xe5, 0xe2, 0x41,
	0xb6, 0x5c, 0x48, 0x01, 0x45, 0x3b, 0x96, 0x00, 0x90, 0x52, 0xc4, 0xa3, 0x02, 0xe2, 0x26, 0x25,
	0x06, 0x21, 0x7f, 0x2e, 0x2e, 0x84, 0x5b, 0x85, 0xe4, 0x50, 0xb4, 0x60, 0x84, 0x88, 0x94, 0x3c,
	0x4e, 0x79, 0x98, 0x81, 0x4e, 0x2c, 0x51, 0x4c, 0x05, 0x49, 0x49, 0x6c, 0xe0, 0xa8, 0x31, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x55, 0x30, 0xbb, 0xd5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LaptopServiceClient is the client API for LaptopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LaptopServiceClient interface {
	CreateLaptop(ctx context.Context, in *CreateLaptopRequest, opts ...grpc.CallOption) (*CreateLaptopResponse, error)
	FindLaptop(ctx context.Context, in *FindLaptopRequest, opts ...grpc.CallOption) (*FindLaptopResponse, error)
}

type laptopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLaptopServiceClient(cc grpc.ClientConnInterface) LaptopServiceClient {
	return &laptopServiceClient{cc}
}

func (c *laptopServiceClient) CreateLaptop(ctx context.Context, in *CreateLaptopRequest, opts ...grpc.CallOption) (*CreateLaptopResponse, error) {
	out := new(CreateLaptopResponse)
	err := c.cc.Invoke(ctx, "/example.com.LaptopService/CreateLaptop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laptopServiceClient) FindLaptop(ctx context.Context, in *FindLaptopRequest, opts ...grpc.CallOption) (*FindLaptopResponse, error) {
	out := new(FindLaptopResponse)
	err := c.cc.Invoke(ctx, "/example.com.LaptopService/FindLaptop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaptopServiceServer is the server API for LaptopService service.
type LaptopServiceServer interface {
	CreateLaptop(context.Context, *CreateLaptopRequest) (*CreateLaptopResponse, error)
	FindLaptop(context.Context, *FindLaptopRequest) (*FindLaptopResponse, error)
}

// UnimplementedLaptopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedLaptopServiceServer struct {
}

func (*UnimplementedLaptopServiceServer) CreateLaptop(ctx context.Context, req *CreateLaptopRequest) (*CreateLaptopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLaptop not implemented")
}
func (*UnimplementedLaptopServiceServer) FindLaptop(ctx context.Context, req *FindLaptopRequest) (*FindLaptopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLaptop not implemented")
}

func RegisterLaptopServiceServer(s *grpc.Server, srv LaptopServiceServer) {
	s.RegisterService(&_LaptopService_serviceDesc, srv)
}

func _LaptopService_CreateLaptop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLaptopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaptopServiceServer).CreateLaptop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.com.LaptopService/CreateLaptop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaptopServiceServer).CreateLaptop(ctx, req.(*CreateLaptopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaptopService_FindLaptop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLaptopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaptopServiceServer).FindLaptop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.com.LaptopService/FindLaptop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaptopServiceServer).FindLaptop(ctx, req.(*FindLaptopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LaptopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.com.LaptopService",
	HandlerType: (*LaptopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLaptop",
			Handler:    _LaptopService_CreateLaptop_Handler,
		},
		{
			MethodName: "FindLaptop",
			Handler:    _LaptopService_FindLaptop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "laptop_service.proto",
}
